SELECT DISTINCT ?specstar ?specstar_spectroscopic_subclass WHERE {

?specstar a <http://www.semanticweb.org/skyserver/SpecStar>.

?specstar <http://www.semanticweb.org/skyserver/Spectroscopy#spectroscopic_subclass> ?specstar_spectroscopic_subclass.

FILTER (contains(lcase(str(?specstar_spectroscopic_subclass)), "wdhotter"))

}

LIMIT 100