SELECT DISTINCT ?starburstgalaxy ?starburstgalaxy_velocity_dispersion WHERE {

?starburstgalaxy a <http://www.semanticweb.org/skyserver/StarBurstGalaxy>.

?starburstgalaxy <http://www.semanticweb.org/skyserver/Spectroscopy#velocity_dispersion> ?starburstgalaxy_velocity_dispersion.

FILTER (?starburstgalaxy_velocity_dispersion > 800 )

}

LIMIT 100