PREFIX : <http://www.semanticweb.org/skyserver/>

SELECT ?q ?ra ?dec ?mag_i ?mag_r ?redshift
WHERE {?q a :SpecQuasar;
            :right_ascension ?ra;
            :declination ?dec;
            :redshift ?redshift ;
            :hasPhotometry ?pq ;
            :hasSpectroWarning "no" .
       ?pq :psfmagnitude_i ?psfmag_i;
           :extinction_i ?extinction_i;
           :psfmagnitude_r ?psfmag_r;
           :extinction_r ?extinction_r;
       BIND((?psfmag_i-?rextinction_i) AS ?mag_i)
       BIND((?psfmag_r-?extinction_r) AS ?mag_r)
} LIMIT 100