SELECT DISTINCT ?specgalaxy ?specgalaxy_declination ?specgalaxy_right_ascension WHERE {

?specgalaxy <http://www.semanticweb.org/skyserver/declination> ?specgalaxy_declination.

?specgalaxy a <http://www.semanticweb.org/skyserver/SpecGalaxy>.

?specgalaxy <http://www.semanticweb.org/skyserver/right_ascension> ?specgalaxy_right_ascension.

FILTER (?specgalaxy_declination > 5 )

FILTER (?specgalaxy_right_ascension < 130 )

}

LIMIT 100