SELECT DISTINCT ?whitedwarf ?whitedwarf_redshift WHERE {

?whitedwarf <http://www.semanticweb.org/skyserver/redshift> ?whitedwarf_redshift.

?whitedwarf a <http://www.semanticweb.org/skyserver/WhiteDwarf>.

FILTER (?whitedwarf_redshift > 0 )

}

LIMIT 100